export enum CategoryName {
    GENERAL_KNOWLEDGE = "General Knowledge",
    BOOKS = "Entertainment: Books",
    FILM = "Entertainment: Film",
    MUSIC = "Entertainment: Music",
    MUSICALS_THEATRES = "Entertainment: Musicals & Theatres",
    TELEVISION = "Entertainment: Television",
    VIDEO_GAMES = "Entertainment: Video Games",
    BOARD_GAMES = "Entertainment: Board Games",
    SCIENCE_NATURE = "Science & Nature",
    COMPUTERS = "Science: Computers",
    MATHEMATICS = "Science: Mathematics",
    MYTHOLOGY = "Mythology",
    SPORTS = "Sports",
    GEOGRAPHY = "Geography",
    HISTORY = "History",
    POLITICS = "Politics",
    ART = "Art",
    CELEBRITIES = "Celebrities",
    ANIMALS = "Animals",
    VEHICLES = "Vehicles",
    COMICS = "Entertainment: Comics",
    GADGETS = "Science: Gadgets",
    ANIME_MANGA = "Entertainment: Japanese Anime & Manga",
    CARTOON_ANIMATIONS = "Entertainment: Cartoon & Animations"
};

export enum CategoryIcon {
    GENERAL_KNOWLEDGE = "fa-brain",
    BOOKS = "fa-book",
    FILM = "fa-film",
    MUSIC = "fa-music",
    MUSICALS_THEATRES = "fa-masks-theater",
    TELEVISION = "fa-tv",
    VIDEO_GAMES = "fa-gamepad",
    BOARD_GAMES = "fa-dice",
    SCIENCE_NATURE = "fa-atoms",
    COMPUTERS = "fa-laptop-code",
    MATHEMATICS = "fa-calculator",
    MYTHOLOGY = "fa-dragon",
    SPORTS = "fa-football",
    GEOGRAPHY = "fa-earth-americas",
    HISTORY = "fa-monument",
    POLITICS = "fa-landmark",
    ART = "fa-palette",
    CELEBRITIES = "fa-star",
    ANIMALS = "fa-paw",
    VEHICLES = "fa-car",
    COMICS = "fa-user-ninja",
    GADGETS = "fa-mobile-screen",
    ANIME_MANGA = "fa-user-ninja",
    CARTOON_ANIMATIONS = "fa-user-ninja"
};