export enum CategoryName {
    GENERAL_KNOWLEDGE = "General Knowledge",
    BOOKS = "Entertainment: Books",
    FILM = "Entertainment: Film",
    MUSIC = "Entertainment: Music",
    MUSICALS_THEATRES = "Entertainment: Musicals & Theatres",
    TELEVISION = "Entertainment: Television",
    VIDEO_GAMES = "Entertainment: Video Games",
    BOARD_GAMES = "Entertainment: Board Games",
    SCIENCE_NATURE = "Science & Nature",
    COMPUTERS = "Science: Computers",
    MATHEMATICS = "Science: Mathematics",
    MYTHOLOGY = "Mythology",
    SPORTS = "Sports",
    GEOGRAPHY = "Geography",
    HISTORY = "History",
    POLITICS = "Politics",
    ART = "Art",
    CELEBRITIES = "Celebrities",
    ANIMALS = "Animals",
    VEHICLES = "Vehicles",
    COMICS = "Entertainment: Comics",
    GADGETS = "Science: Gadgets",
    ANIME_MANGA = "Entertainment: Japanese Anime & Manga",
    CARTOON_ANIMATIONS = "Entertainment: Cartoon & Animations"
};